#!/bin/bash
#
# Take a backup of the MySQL database
#

# Current date for adding to filename
now=$(date +"%Y-%m-%d")

# Set filenames for dumps
basedir="/tmp/"
file_structure=$basedir"db-structure_"$now".sql"
file_data=$basedir"db-data_"$now".sql.gz"

# Prompt for mysql password
echo "Enter the mysql password and press [ENTER]"
read -s password

echo "Dumping structure..."
# Export all create-statements
mysqldump -u root -p$password --all-databases --no-data --skip-quote-names --opt  > $file_structure

echo "Dumping data..."
# Export all data
# Gzip level 9 means best compression, might be slow for big chunks of data.
mysqldump -u root -p$password --no-create-db --no-create-info --opt \
	--databases clickTrackr ftpusers mma systemHealth phpunit mysql \
	| gzip -9 > $file_data
