#!/bin/bash
#
# Install required packages
# Copy all required config files
#
#

if [ "$(id -u)" != "0" ]; then
	echo "You need to be root to execute this script"
	exit 1
fi


# Install packages
apt-get update
apt-get install -y \
	git \
	samba \
	isc-dhcp-server \
	shorewall shorewall-core \
	nginx-light \
	make \
	php5 php-pear php5-cli php5-common php5-curl php5-mcrypt \
	php5-dev php5-fpm php5-json php5-mysql php5-readline \
	mysql-server \
	memcached libmemcached-dev \
	transmission transmission-cli transmission-daemon \
	gettext


echo "#################################################"
echo " Packages installed"
echo " Installing PEAR & PECL"
echo "#################################################"

# Install PEAR & PECL-extensions
pear config-set auto_discover 1
pecl install xdebug
# Version 2.1.0 isn't working right now :(
pecl install -f --alldeps memcached-2.0.0
pear install --alldeps pear.phpunit.de/PHPUnit


DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "#################################################"
echo " Copying config files"
echo "#################################################"

# Copy config files
cp -r $DIR/etc/* /etc

# Enable PECL/PEAR mods
/usr/sbin/php5enmod memcached
/usr/sbin/php5enmod xdebug

# Set correct owner of config files
chown debian-transmission:debian-transmission /etc/transmission-daemon/settings.json

# Create symlinks required
ln -s /etc/nginx/sites-available/site-01 /etc/nginx/sites-enabled/site-01
ln -s /etc/php5/conf.d/miken.ini /etc/php5/fpm/conf.d/miken.ini
ln -s /etc/php5/conf.d/miken.ini /etc/php5/cli/conf.d/miken.ini
# Seems like mcrypt isn't enabled by default
ln -s /etc/php5/conf.d/mcrypt.ini /etc/php5/fpm/conf.d/20-mcrypt.ini
ln -s /etc/php5/conf.d/mcrypt.ini /etc/php5/cli/conf.d/20-mcrypt.ini

# Samba
# If you run this command multiple times, you need to remove the
# extra includes created below in smb.conf
echo "" >> /etc/samba/smb.conf
echo "include = /etc/samba/miken.conf" >> /etc/samba/smb.conf

# Reload/restart services
service php5-fpm restart
service nginx restart
service samba restart
service networking restart
service isc-dhcp-server restart
service shorewall restart
service transmission-daemon restart

echo "#################################################"
echo " Done!"
echo ""
echo "              !!  IMPORTANT !!"
echo " To enable shorewall, you need to modify"
echo " /etc/default/shorewall and set startup=1"
echo ""
echo " and add the DHCP-interface to:"
echo " /etc/default/isc-dhcp-server"
echo "#################################################"
