#!/bin/bash
#
# Install required packages
# Copy all required config files
#
#

if [ "$(id -u)" != "0" ]; then
	echo "You need to be root to execute this script"
	exit 1
fi


# Install packages
apt-get update
apt-get install -y \
	git \
	samba \
	shorewall shorewall-core \
	nginx-light \
	php5 php5-dev php5-cli php5-fpm php5-json php-pear php5-curl php5-mysql \
	mysql-server \
	memcached libmemcached-dev \
	transmission transmission-cli transmission-daemon

# Install PEAR & PECL-extensions
pear config-set auto_discover 1
pecl install xdebug memcached
pear install --alldeps pear.phpunit.de/PHPUnit


DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Copy config files
cp -r $DIR/etc/* /etc

# Nginx
ln -s /etc/nginx/sites-available/site-01 /etc/nginx/sites-enabled/site-01

# Samba
echo "" >> /etc/samba/smb.conf
echo "include = /etc/samba/miken.conf" >> /etc/samba/smb.conf
