#!/bin/bash
#
# Install required packages
# Copy all required config files
#
#

if [ "$(id -u)" != "0" ]; then
	echo "You need to be root to execute this script"
	exit 1
fi


# Install packages
apt-get update
apt-get install -y \
	git \
	samba \
	shorewall shorewall-core \
	nginx-light \
	make \
	php5 php-pear php5-cli php5-common php5-curl \
	php5-dev php5-fpm php5-json php5-mysql php5-readline \
	mysql-server \
	memcached libmemcached-dev \
	transmission transmission-cli transmission-daemon

echo "##################################################\n"
echo " Packages installed\n"
echo " Installing PEAR & PECL\n"
echo "##################################################\n"

# Install PEAR & PECL-extensions
pear config-set auto_discover 1
pecl install xdebug memcached
pear install --alldeps pear.phpunit.de/PHPUnit


DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "##################################################\n"
echo " Copying config files\n"
echo "##################################################\n"

# Copy config files
cp -r $DIR/etc/* /etc

# Nginx
ln -s /etc/nginx/sites-available/site-01 /etc/nginx/sites-enabled/site-01

# Samba
echo "" >> /etc/samba/smb.conf
echo "include = /etc/samba/miken.conf" >> /etc/samba/smb.conf

# Transmission
/etc/init.d/transmission-daemon reload

echo "##################################################\n"
echo " Done!\n"
echo "##################################################\n"
