#!/bin/bash
#
# Remove all packages installed
#

# Uninstall PEAR & PECL-extensions
pecl uninstall xdebug memcached
pear uninstall --alldeps pear.phpunit.de/PHPUnit

# Remove packages (except git)
apt-get remove --purge \
	samba \
	shorewall shorewall-core \
	nginx-light \
	make \
	php5 php-pear php5-cli php5-common php5-curl \
	php5-dev php5-fpm php5-json php5-mysql php5-readline \
	mysql-server \
	memcached libmemcached-dev \
	transmission transmission-cli transmission-daemon

# Clean up left over packages
apt-get autoremove

# Remove some config files / links
rm -f /etc/nginx/sites-enabled/site-01
