#!/bin/bash
#
# Update config files
#

if [ "$(id -u)" != "0" ]; then
	echo "You need to be root to execute this script"
	exit 1
fi


DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "#################################################"
echo " Updating config files"

# Copy config files
cp -r $DIR/etc/* /etc

# Reload/restart services
service php5-fpm restart
service nginx restart
service samba restart
service networking restart
service isc-dhcp-server restart
service shorewall restart
service transmission-daemon restart

echo "#################################################"
echo " Done!"
